### ISSUE TITLE
STUCK ON CONNECTING TO "UK, SCOTLAND, ... WITH HMA-VPN.SH

### ISSUE THREAD

**Issue by LunarDevelopment** [milansky/HMA-VPN#1]
Hey! 

I really hope you can help, this looks to be an ongoing issue within GMA support forum. 

I'm using a virtual machine running debian 9.2, last time I used it a few months ago, my script was working fine. 

Now I've tried my older versions of hma-vpn.sh and replaced them with the latest `hma-vpn.sh` (I see it was updated march 2021 on HMA site) but my command line seems to be stuck on either "Connecting to " a vpn or "Disconnected" when I run : 

`sudo bash /home/hma/hma-vpn.sh -d -p tcp -c credentials gb.hma.rocks`

No matter how long I wait, it will not finish connecting to a server, "credentials" are a valid file in that path and working through desktop application. 

* Same behaviour no matter where I connect to, with the above command. 

** When I go through the `hma-openvpn.sh` script, it gets stuck on Initialization Sequence Completed, no matter how long I wait.

**Comment by milansky** [comment]
I apologize for the late reply.

Initialization Sequence Completed - this means that you are connected to the VPN.
Haven't checked on the script in a very long time and looks like HMA dropped support for Linux :(
